### ISSUE TITLE
Duplicate words across headline and body in org-mode

### ISSUE THREAD

**Issue by dowcet** [bnbeckwith/writegood-mode#10]
I typically use writegood in org-mode, and have encountered a situation like this:
```
* Title of a Section on Foo
Foo is good.
```
Here writegood sees "Foo" as a duplicate word. That in itself might not be a problem, but it messes with the color/face of the whole headline and makes it look like normal text. 

I'm not sure if writegood could indicate the duplication in a way that won't mess up the appearance of org-mode headlines, but if not, I think it might be better for writegood to ignore duplication in such specific cases.

**Comment by bnbeckwith** [comment]
This issue is now fixed in v2.0.2.  Thanks!
