### ISSUE TITLE
Words Are Not Underlined/Highlighted When Running Under Markdown Mode

### ISSUE THREAD

**Issue by sshaw** [bnbeckwith/writegood-mode#12]
- Writegood mode 2.0
- Makrdown mode 20150703.1903.
- Emacs 24.4.1

Markdown mode is derived from text mode. This is not a problem in text mode.

**Comment by bnbeckwith** [comment]
I cannot replicate this issue. 

I have markdown mode from 20151108.735. I don't know if that is the difference.  Can anyone else replace this failure?

**Comment by sbacelar** [comment]
It does not work in md files but works on txt or org files.

Writegood mode 2.0
Markdown mode 2.1
Emacs 24.5.1

**Comment by anarcat** [comment]
works well for me in markdown 2.1, writegood 2.1 and emacs 25.1.1, with solarized theme.

maybe it's a theme issue?

**Comment by bnbeckwith** [comment]
@sshaw @sbacelar  Is this still an issue for you?

**Comment by sshaw** [comment]
Working with: 

* Markdown 2.1
* Writegood 2.1 
* Emacs 24.5.1

**Comment by bnbeckwith** [comment]
I don't know that this is still a problem, so I'm closing this issue.
