### ISSUE TITLE
Triple dot messes up Flesch–Kincaid's scores

### ISSUE THREAD

**Issue by dangom** [bnbeckwith/writegood-mode#15]
I guess triple-dots end up being counted as multiple sentences. 

How does one properly add "..." to `writegood-sentence-punctuation`? A naive attempt to simply add "..." [here](https://github.com/bnbeckwith/writegood-mode/blob/master/writegood-mode.el#L149) breaks `writegood-grade-level`.

**Comment by bnbeckwith** [comment]
The current punctuation implementation looks for a single character. If you have three periods, then it will count as three sentences. 

However, if you use an ellipsis (codepoint 8230, #o20046, #x2026) as a punctuation character, you can have the scores evaluate correctly.
