### ISSUE TITLE
Fails to do check when enabled via add-hook

### ISSUE THREAD

**Issue by powellb** [bnbeckwith/writegood-mode#16]
I have added writegood-mode to a hook for LaTeX-mode:

(add-hook 'LaTeX-mode-hook 'writegood-mode))

When I open a latex file, writegood-mode is enabled; however, it doesn't highlight any of the trouble areas. If I execute writegood-mode, it disables writegood. If I execute again, writegood-mode is enabled and the highlighting works as normal.

Any idea why it wouldn't work when enabled via another mode-hook?

**Comment by dangom** [comment]
Not the author, but hooks work for me. 
If you try:
(add-hook 'LaTeX-mode-hook 'writegood-turn-on), does it then work?

**Comment by powellb** [comment]
Thanks for the suggestion; however, writegood-turn-on is not one of its autoload functions, so it is not available after requiring the package. As such, nothing happens with the hook.

**Comment by bnbeckwith** [comment]
@powellb `writegood-mode` relies on `font-lock-mode`.  Is it possible that other hooks are messing around with `font-lock-mode`?

I'll try more to see if I can narrow down the issue and get a resolution.

**Comment by bnbeckwith** [comment]
@powellb, did you ever find a resolution to this issue?

**Comment by powellb** [comment]
I did not. I simply enable the mode by hand when I am interested in using it.

**Comment by bnbeckwith** [comment]
I'm closing this as I could not recreate the issue.

**Comment by averter** [comment]
Hello. I am experiencing exactly the same issue as @powellb . There is a similar issue reported [here](https://tex.stackexchange.com/questions/272320/emacs-auctex-preserve-highlights-from-other-modes-after-apply-style-hooks) but I couldn't get it to work with an hook on the TeX-update-style-hook. I've also tried to deactivate other modes that provide highlighting (such as flyspell) but no joy so far...
