### ISSUE TITLE
Writegood-mode capitalizes latex-pretty-symbols greek characters.

### ISSUE THREAD

**Issue by sunbubble** [bnbeckwith/writegood-mode#22]
**latex-pretty-symbols** does the following:
If I type 
> $\xi$ is a greek letter

it will change it to 
> $ξ$ is a greek letter

If I then activate **writegood-mode** the string then becomes
> $Ξ$ is a greek letter

and doesn't change back on deactivation.
The dollar signs just mark the inline math mode, the problem persists even if I try this without them.

Thanks in advance for any help.

**Comment by bnbeckwith** [comment]
I'm afraid that I couldn't recreate this issue and I'm closing it.  Please let me know if you have more detail on the issue and potential fix.
