### ISSUE TITLE
Hook into flyspell?

### ISSUE THREAD

**Issue by robstewart57** [bnbeckwith/writegood-mode#26]
How would I add a writegood-mode hook into FlySpell, such that when flyspell mode is enabled, writegood-mode also becomes enabled?

**Comment by bnbeckwith** [comment]
Hi @robstewart57. To do this, you can use the hooks in `flyspell-mode`. It will look something like this: 

```lisp
(add-to-list 'flyspell-mode-hook #'writegood-mode)
```
