### ISSUE TITLE
Show the meaning of the error at point in the minibuffer 

### ISSUE THREAD

**Issue by maikol-solis** [bnbeckwith/writegood-mode#32]
Hi! 

When I use this package, sometimes I don't understand why some word is highlighted. I need to review the link to the README (https://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/) to understand the reason. 

I would be great if the package throws some explanation in the minibuffer about the error at point. 

Thanks.

**Comment by bnbeckwith** [comment]
@maikol-solis Thanks for the suggestion!  The implementation of this feature (v2.2.0) leverages the `help-echo` text property. This means that by default is shows as a tooltip on graphical displays. 

For more ways to customize how the messages display consider https://www.gnu.org/software/emacs/manual/html_node/emacs/Help-Echo.html
