### ISSUE TITLE
Regular expressions query

### ISSUE THREAD

**Issue by revcomninos** [bnbeckwith/writegood-mode#33]
Can I add regex to Writegood Weasel Words? For example, say I want to find phrases like this:
Beth-Rehob.
Where we have a word followed by a hyphen followed by a capital word?
I tried "-[A-Z]+" and it brought up nothing.
If I type only "-" then it highlights the hyphen.

**Comment by revcomninos** [comment]
Anyone out there?

**Comment by bnbeckwith** [comment]
Hi @revcomninos. Sorry to leave you hanging. This required an addition to the code which I've made in version 2.1.0. There are now two additional custom variables that let you add in your own custom regexps. 

In your case, you'll want to set `writegood-weasel-words-additional-regexp` to your desired regexp.

**Comment by revcomninos** [comment]
Many thanks.
